### ISSUE TITLE
demo test3.py cannot display image

### ISSUE THREAD

**Issue by zixijian** [termux/termux-gui#22]
```
[~]$ python test3.py 1.png
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test3.py", line 11, in <module>
    with open("icon.png","rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'icon.png'
```
delete line 11
```
[~]$ python test3.py 1.png
/data/data/com.termux/files/usr/bin/sh: 1: identify: not found
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test3.py", line 50, in <module>
    sock.bind("\0test")
OSError: [Errno 98] Address already in use
```

**Comment by tareksander** [comment]
The lower-numbered demo scripts come from an earlier testing phase and may not work. If you want working and up-to-date demo code, see the [python bindings tutorial](https://github.com/tareksander/termux-gui-python-bindings/tree/main/tutorial).
