### ISSUE TITLE
base-64 error

### ISSUE THREAD

**Issue by Vosjedev** [termux/termux-gui#40]
I tried running an example from the examples. The example was the files one.
I found this error in the termyx-gui logcat:
```
07-05 08:12:11.809 21783 22852 W System.err: java.lang.IllegalArgumentException: bad base-64
07-05 08:12:11.810 21783 22852 W System.err: 	at android.util.Base64.decode(Base64.java:163)
07-05 08:12:11.810 21783 22852 W System.err: 	at android.util.Base64.decode(Base64.java:138)
07-05 08:12:11.810 21783 22852 W System.err: 	at android.util.Base64.decode(Base64.java:120)
07-05 08:12:11.810 21783 22852 W System.err: 	at com.termux.gui.protocol.json.v0.HandleActivityAndTask$Companion$handleActivityTaskMessage$6.invoke(HandleActivityAndTask.kt:114)
07-05 08:12:11.811 21783 22852 W System.err: 	at com.termux.gui.protocol.json.v0.HandleActivityAndTask$Companion$handleActivityTaskMessage$6.invoke(HandleActivityAndTask.kt:107)
07-05 08:12:11.811 21783 22852 W System.err: 	at com.termux.gui.protocol.shared.v0.V0Shared$Companion$runOnUIThreadActivityStarted$1$1.invokeSuspend(V0Shared.kt:247)
07-05 08:12:11.811 21783 22852 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-05 08:12:11.811 21783 22852 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-05 08:12:11.811 21783 22852 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
07-05 08:12:11.811 21783 22852 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-05 08:12:11.811 21783 22852 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
07-05 08:12:11.811 21783 22852 W System.err: 	at android.os.Looper.loop(Looper.java:313)
07-05 08:12:11.811 21783 22852 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8669)
07-05 08:12:11.811 21783 22852 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-05 08:12:11.811 21783 22852 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
07-05 08:12:11.811 21783 22852 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

this was the output of the script (the stacktrace):
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/termux-gui/./files.in", line 41, in <module>
    layout = tg.LinearLayout(a)
             ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/termuxgui/linearlayout.py", line 16, in __init__
    ViewGroup.__init__(self, activity, activity.c.send_read_msg({"method": "createLinearLayout", "params": args}))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/termuxgui/connection.py", line 145, in send_read_msg
    return self.__read_msg()
           ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/termuxgui/connection.py", line 138, in __read_msg
    return tgmsg.read_msg(self._main)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/termuxgui/msg.py", line 11, in read_msg
    read = s.recv(togo)
           ^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
```

[here is a pastebin of the complete logcat.](https://pastebin.com/QTTwRbUk)

**Comment by tareksander** [comment]
It's a .in file, not a .py file. For readability, the base64 string of the icon is compiled in with cmake. I assume it's from the termux-gui-package repo?

**Comment by Vosjedev** [comment]
Oh sorry I just found out... Sorry I had to read the whole readme I guess...

**Comment by Vosjedev** [comment]
How do I use that? just `make` then `make install`? I found out it is a C related file.

**Comment by tareksander** [comment]
`cmake .` then `make install`. But if you don't want to modify the scripts, you can `pkg i termux-gui-package` instead.

**Comment by tareksander** [comment]
If you want to learn how to use Termux:GUI, see the [Python tutorial](https://github.com/tareksander/termux-gui-python-bindings/blob/main/TUTORIAL.md) instead.

**Comment by tareksander** [comment]
If it's not clear, you can reopen the issue.
